[package]
name = "protocol-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.7", features = ["ws"] }
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
futures = "0.3"
serde_json = "1.0"

[profile.release]
panic = 'abort'

[profile.dev]
panic = 'abort'